Fix Syntax Error

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -26,7 +26,7 @@ jobs:
       - name: Check
         run: |
           if [[ "${{ github.event.inputs.environment }}" == "production" && "${{ github.event.inputs.image }}" == "pr" ]]; then
-            echo "ERROR: Can't deploy PR image to the production environment" > &2
+            echo "ERROR: Can't deploy PR image to the production environment" >&2
             exit 1
           fi
 
