Fix: DB Name Depending On The Environment [skip ci]
Signed-off-by: dejanakop <dkop@griddynamics.com>

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -20,20 +20,20 @@ on:
 
 jobs:
 
-  # check_if_allowed:
-  #   runs-on: self-hosted
-  #   steps:
-  #     - name: Check
-  #       run: |
-  #         if [[ "${{ github.event.inputs.environment }}" == "production" && "${{ github.event.inputs.image }}" == "pr" ]]; then
-  #           echo "ERROR: Can't deploy PR image to the production environment" >&2
-  #           exit 1
-  #         fi
+  check_if_allowed:
+    runs-on: self-hosted
+    steps:
+      - name: Check
+        run: |
+          if [[ "${{ github.event.inputs.environment }}" == "production" && "${{ github.event.inputs.image }}" == "pr" ]]; then
+            echo "ERROR: Can't deploy PR image to the production environment" >&2
+            exit 1
+          fi
 
   deploy_petclinic:
 
     runs-on: self-hosted
-    # needs: check_if_allowed
+    needs: check_if_allowed
     steps:
   
       - name: Checkout
@@ -78,11 +78,18 @@ jobs:
           else
             IMAGE="${{ vars.REGION }}-docker.pkg.dev/${{ secrets.PROJECT }}/${{ secrets.PR_REPO }}/spring-petclinic:latest"
           fi
+
+          if [[ "${{ github.event.inputs.environment }}" == "production" ]]; then
+            DB_NAME=${{ secrets.PRODUCTION_DB_NAME }}
+          else
+            DB_NAME=${{ secrets.DEV_DB_NAME }}
+          fi
+          
           helm dependency build ./helm/petclinic/
           helm upgrade --install petclinic ./helm/petclinic/ \
             --set deployment.image=$IMAGE \
             --set db.url=${{ secrets.DB_HOST }} \
-            --set db.name=${{ secrets.DB_NAME }} \
+            --set db.name=$DB_NAME \
             --set db.user=${{ secrets.DB_USER }} \
             --set db.password=${{ secrets.DB_PASSWORD }}
 
